### ISSUE TITLE
Data extraction failed

### ISSUE THREAD

**Issue by Joysond** [fcorti/Alflytics#10]
Hi ,
I am trying to extract data (http://localhost:9000/pentaho/plugin/Alflytics/api/extract) and I get the following exception.

`org.pentaho.di.core.exception.KettleStepException: 
Error while running this step!

Couldn't execute SQL: INSERT INTO "DWH_DIM_DATES_YEARS" ("ID","DESCRIPTION") 
(
  SELECT -1.0 AS "ID", 'Unknown' AS "DESCRIPTION"
)
ON CONFLICT ("ID") DO UPDATE SET 
 "DESCRIPTION"=EXCLUDED."DESCRIPTION"

ERROR: syntax error at or near "ON"
  Position: 111

	at org.pentaho.di.trans.steps.sql.ExecSQL.processRow(ExecSQL.java:236)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
Couldn't execute SQL: INSERT INTO "DWH_DIM_DATES_YEARS" ("ID","DESCRIPTION") 
(
  SELECT -1.0 AS "ID", 'Unknown' AS "DESCRIPTION"
)
ON CONFLICT ("ID") DO UPDATE SET 
 "DESCRIPTION"=EXCLUDED."DESCRIPTION"

ERROR: syntax error at or near "ON"
  Position: 111

	at org.pentaho.di.core.database.Database.execStatement(Database.java:1561)
	at org.pentaho.di.core.database.Database.execStatements(Database.java:1661)
	at org.pentaho.di.trans.steps.sql.ExecSQL.processRow(ExecSQL.java:211)
	... 2 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 111
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:397)
	at org.pentaho.di.core.database.Database.execStatement(Database.java:1535)
	... 4 more
2018/01/08 18:48:57 - Execute SQL script.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2018/01/08 18:48:57 - Execute SQL script.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2018/01/08 18:48:57 - Execute SQL script.0 - Error while running this step!
2018/01/08 18:48:57 - Execute SQL script.0 - 
2018/01/08 18:48:57 - Execute SQL script.0 - Couldn't execute SQL: INSERT INTO "DWH_DIM_DATES_YEARS" ("ID","DESCRIPTION") 
2018/01/08 18:48:57 - Execute SQL script.0 - (
2018/01/08 18:48:57 - Execute SQL script.0 -   SELECT -1.0 AS "ID", 'Unknown' AS "DESCRIPTION"
2018/01/08 18:48:57 - Execute SQL script.0 - )
2018/01/08 18:48:57 - Execute SQL script.0 - ON CONFLICT ("ID") DO UPDATE SET 
2018/01/08 18:48:57 - Execute SQL script.0 -  "DESCRIPTION"=EXCLUDED."DESCRIPTION"
2018/01/08 18:48:57 - Execute SQL script.0 - 
2018/01/08 18:48:57 - Execute SQL script.0 - ERROR: syntax error at or near "ON"
2018/01/08 18:48:57 - Execute SQL script.0 -   Position: 111
2018/01/08 18:48:57 - Execute SQL script.0 - 
2018/01/08 18:48:57 - Execute SQL script.0 - 
2018/01/08 18:48:57 - Execute SQL script.0 - 	at org.pentaho.di.trans.steps.sql.ExecSQL.processRow(ExecSQL.java:236)
2018/01/08 18:48:57 - Execute SQL script.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/01/08 18:48:57 - Execute SQL script.0 - 	at java.lang.Thread.run(Thread.java:745)
2018/01/08 18:48:57 - Execute SQL script.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2018/01/08 18:48:57 - Execute SQL script.0 - Couldn't execute SQL: INSERT INTO "DWH_DIM_DATES_YEARS" ("ID","DESCRIPTION") 
2018/01/08 18:48:57 - Execute SQL script.0 - (
2018/01/08 18:48:57 - Execute SQL script.0 -   SELECT -1.0 AS "ID", 'Unknown' AS "DESCRIPTION"
2018/01/08 18:48:57 - Execute SQL script.0 - )
2018/01/08 18:48:57 - Execute SQL script.0 - ON CONFLICT ("ID") DO UPDATE SET 
2018/01/08 18:48:57 - Execute SQL script.0 -  "DESCRIPTION"=EXCLUDED."DESCRIPTION"
2018/01/08 18:48:57 - Execute SQL script.0 - 
2018/01/08 18:48:57 - Execute SQL script.0 - ERROR: syntax error at or near "ON"
2018/01/08 18:48:57 - Execute SQL script.0 -   Position: 111
2018/01/08 18:48:57 - Execute SQL script.0 - 
2018/01/08 18:48:57 - Execute SQL script.0 - 	at org.pentaho.di.core.database.Database.execStatement(Database.java:1561)
2018/01/08 18:48:57 - Execute SQL script.0 - 	at org.pentaho.di.core.database.Database.execStatements(Database.java:1661)
2018/01/08 18:48:57 - Execute SQL script.0 - 	at org.pentaho.di.trans.steps.sql.ExecSQL.processRow(ExecSQL.java:211)
2018/01/08 18:48:57 - Execute SQL script.0 - 	... 2 more
2018/01/08 18:48:57 - Execute SQL script.0 - Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
2018/01/08 18:48:57 - Execute SQL script.0 -   Position: 111`

And when I go to url http://localhost:9000/pentaho/plugin/Alflytics/api/check 
there are couple of extraction extraction logs failed they are **Alfresco users in warehouse, Alfresco audit trail in warehouse, Alfresco repository in warehouse, Alfresco processes in staging** and 
**Data quality** is empty.

Any help would be of great help

Thanks.

**Comment by fcorti** [comment]
Hi,

Can you please confirm you are using PostgreSql as DB for the Alflytics warehouse?

Do you get the same error if you try to run the Get All job using the Spoon User Interface?

Cheers.

**Comment by Joysond** [comment]
Hi,

I am using PostgreSql as DB for Alflytics warehouse and I do not get any errors for **Get All** job in Spoon UI

Thanks

**Comment by fcorti** [comment]
Hi again,

I received a notification that I cannot see anymore here?
Perhaps you deleted it.

Any update on this?

**Comment by Joysond** [comment]
I am not able to run from spoon UI too. I get below error

2018/01/09 12:59:03 - Get REST in json for audit trail - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35.36 by buildguy) : java.lang.StackOverflowError
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.net.SocketInputStream.socketRead0(Native Method)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.http.HttpClient.available(HttpClient.java:380)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.http.HttpClient.New(HttpClient.java:276)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:120)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:256)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:184)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:109)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:641)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:600)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:585)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:482)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.client.Stub.process(Stub.java:323)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:161)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:113)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:93)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:144)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.proxy.$Proxy84.getFile(Unknown Source)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.lang.reflect.Method.invoke(Method.java:498)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.repository.pur.UnifiedRepositoryInvocationHandler.invoke(UnifiedRepositoryInvocationHandler.java:39)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.proxy.$Proxy85.getFile(Unknown Source)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.platform.repository2.unified.webservices.jaxws.UnifiedRepositoryToWebServiceAdapter.getFile(UnifiedRepositoryToWebServiceAdapter.java:276)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.lang.reflect.Method.invoke(Method.java:498)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.repository.pur.UnifiedRepositoryInvocationHandler.invoke(UnifiedRepositoryInvocationHandler.java:39)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.proxy.$Proxy100.getFile(Unknown Source)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory.findDirectory(LazyUnifiedRepositoryDirectory.java:100)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory.findDirectory(LazyUnifiedRepositoryDirectory.java:50)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.repository.pur.PurRepository.findDirectory(PurRepository.java:2667)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at java.lang.reflect.Method.invoke(Method.java:498)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.ui.repo.RepositorySessionTimeoutHandler.invoke(RepositorySessionTimeoutHandler.java:71)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at com.sun.proxy.$Proxy65.findDirectory(Unknown Source)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.job.entries.trans.JobEntryTrans.getTransMeta(JobEntryTrans.java:1256)
2018/01/09 12:59:03 - Get REST in json for audit trail - 	at org.pentaho.di.job.entries.trans.JobEntryTrans.execute(JobEntryTrans.java:677)

**Comment by Joysond** [comment]
I am using postgresql as DB for Alflytics warehouse

 I see below exceptions keep repeating
 
2018/01/09 14:55:19 - Get REST in json for audit trail - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleException: 

2018/01/09 14:54:37 - Get REST in json for audit trail -  at org.pentaho.di.job.entries.trans.JobEntryTrans.execute (JobEntryTrans.java:683)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at org.pentaho.di.core.Const.getStackTracker (Const.java:2580)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at org.pentaho.di.core.Const.getClassicStackTrace (Const.java:2586)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at java.lang.Throwable.printStackTrace (Throwable.java:721)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at java.lang.Throwable.printStackTrace (Throwable.java:655)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at java.lang.Throwable$WrappedPrintWriter.println (Throwable.java:764)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at java.io.PrintWriter.println (PrintWriter.java:754)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at java.lang.String.valueOf (String.java:2994)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at java.lang.Throwable.toString (Throwable.java:480)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at java.lang.Throwable.getLocalizedMessage (Throwable.java:391)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at org.pentaho.di.core.exception.KettleException.getMessage (KettleException.java:89)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at org.pentaho.di.core.exception.KettleException.getMessage (KettleException.java:89)
2018/01/09 14:54:37 - Get REST in json for audit trail -  at org.pentaho.di.core.exception.KettleException.getMessage (KettleException.java:98)

Thanks

**Comment by fcorti** [comment]
Hi,

The first error (java.lang.StackOverflowError) is related to few memory available for Spoon.
The other error is not clear enough.
I suggestion you to solve the first, before, extending the RAM for it.

Let me know how it goes.

**Comment by Joysond** [comment]
Hi, 

I have increase the memory for spoon and still no luck

> PENTAHO_DI_JAVA_OPTIONS="-Xms8g -Xmx10g -XX:MaxPermSize=512m"

If I disable or set property **alflytics.getData.alfresco.entity.audits=false**  in Get From Alfresco then job runs fine but I see below error

` Insert or update the users - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : An error occurred executing this job entry : 
2018/01/10 10:20:44 - Insert or update the users - Couldn't execute SQL: INSERT INTO "DWH_ALF_DIM_USERS" ("ID","ALF_ID","EMAIL","FIRST_NAME","LAST_NAME","ORGANIZATION","IS_EMAIL_NOTIFICATIONS_ENABLED","IS_ENABLED","DT_DELETED","INSTANCE_ID","SRC_ID") 
2018/01/10 10:20:44 - Insert or update the users - (
2018/01/10 10:20:44 - Insert or update the users -  SELECT
2018/01/10 10:20:44 - Insert or update the users -   -1 AS "ID", 'Unknown' AS "ALF_ID", 'Unknown' AS "EMAIL", 'Unknown' AS "FIRST_NAME", 'Unknown' AS "LAST_NAME",
2018/01/10 10:20:44 - Insert or update the users -   'Unknown' AS "ORGANIZATION", FALSE AS "IS_EMAIL_NOTIFICATIONS_ENABLED", TRUE AS "IS_ENABLED", NULL AS "DT_DELETED",
2018/01/10 10:20:44 - Insert or update the users -   1 AS "INSTANCE_ID", 'Unknown' AS "SRC_ID"
2018/01/10 10:20:44 - Insert or update the users - ) 
2018/01/10 10:20:44 - Insert or update the users - ON CONFLICT ("INSTANCE_ID","SRC_ID") DO UPDATE SET 
2018/01/10 10:20:44 - Insert or update the users -  "ID"=EXCLUDED."ID", "ALF_ID"=EXCLUDED."ALF_ID", "EMAIL"=EXCLUDED."EMAIL", "FIRST_NAME"=EXCLUDED."FIRST_NAME", "LAST_NAME"=EXCLUDED."LAST_NAME", 
2018/01/10 10:20:44 - Insert or update the users -  "ORGANIZATION"=EXCLUDED."ORGANIZATION", "IS_EMAIL_NOTIFICATIONS_ENABLED"=EXCLUDED."IS_EMAIL_NOTIFICATIONS_ENABLED", "IS_ENABLED"=EXCLUDED."IS_ENABLED", 
2018/01/10 10:20:44 - Insert or update the users -  "DT_DELETED"=EXCLUDED."DT_DELETED", "INSTANCE_ID"=EXCLUDED."INSTANCE_ID", "SRC_ID"=EXCLUDED."SRC_ID"`

**Comment by Joysond** [comment]
Hi,

I have resolved most of the errors and I get only below listed exception (not while retrieving data from alfresco but while writing to alflytics database)

Couldn't execute SQL: INSERT INTO "DWH_DIM_DATES_YEARS" ("ID","DESCRIPTION")
(
SELECT -1.0 AS "ID", 'Unknown' AS "DESCRIPTION"
)
ON CONFLICT ("ID") DO UPDATE SET
"DESCRIPTION"=EXCLUDED."DESCRIPTION"

ERROR: syntax error at or near "ON"

Any idea why is it happening

Thanks

**Comment by fcorti** [comment]
HI,

What happen if you execute the same command into the PostgreSql client (like Admin3 for example)?
Are you having the same error?

**Comment by Joysond** [comment]
Hi,

Yes I get same error.

Query Executed : `INSERT INTO "DWH_DIM_DATES_YEARS" ("ID","DESCRIPTION") (SELECT -1.0 AS "ID", 'Unknown' AS "DESCRIPTION") ON CONFLICT ("ID") DO UPDATE SET "DESCRIPTION"=EXCLUDED."DESCRIPTION"`

Error message: 

 ERROR:  syntax error at or near "ON"
LINE 1: ...(SELECT -1.0 AS "ID", 'Unknown' AS "DESCRIPTION") ON CONFLIC...
                                                             ^

********** Error **********

ERROR: syntax error at or near "ON"
SQL state: 42601
Character: 106

Thanks

**Comment by fcorti** [comment]
Ok, so it's a problem of PostgreSql version!
Probably the version you are using is not supporting the "ON ..." command.
Please check.

**Comment by fcorti** [comment]
I assume it is solved.
