### ISSUE TITLE
Bug Wrapped Exception (with status template): null

### ISSUE THREAD

**Issue by Silvestre77** [fcorti/Alflytics#11]
2018/05/17 21:23:48 - Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Row nr 1 causing abort : [{}], [http://10.39.17.122:8080/alfresco/service/api/audit/query/alfresco-access?fromId=785000&limit=5000&verbose=true], [GET], [785000,0], [{
2018/05/17 21:23:48 - Abort.0 -     "status" : 
2018/05/17 21:23:48 - Abort.0 -   {
2018/05/17 21:23:48 - Abort.0 -     "code" : 500,
2018/05/17 21:23:48 - Abort.0 -     "name" : "Internal Error",
2018/05/17 21:23:48 - Abort.0 -     "description" : "An error inside the HTTP server which prevented it from fulfilling the request."
2018/05/17 21:23:48 - Abort.0 -   },  
2018/05/17 21:23:48 - Abort.0 -   
2018/05/17 21:23:48 - Abort.0 -   "message" : "04170003 Wrapped Exception (with status template): null",  
2018/05/17 21:23:48 - Abort.0 -   "exception" : "",
2018/05/17 21:23:48 - Abort.0 -   
2018/05/17 21:23:48 - Abort.0 -   "callstack" : 
2018/05/17 21:23:48 - Abort.0 -   [ 
2018/05/17 21:23:48 - Abort.0 -   	   
2018/05/17 21:23:48 - Abort.0 -   ],
2018/05/17 21:23:48 - Abort.0 -   
2018/05/17 21:23:48 - Abort.0 -   "server" : "Community v5.2.0 (re21f2be5-b22) schema 10.057",
2018/05/17 21:23:48 - Abort.0 -   "time" : "17/05/2018 21:23:48"
2018/05/17 21:23:48 - Abort.0 - }
2018/05/17 21:23:48 - Abort.0 - 
2018/05/17 21:23:48 - Abort.0 - ], [500]
2018/05/17 21:23:48 - Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Rest call failed.

**Comment by fcorti** [comment]
Hi @Silvestre77,

The error 500 is on Alfresco's side.
I suggest you to check the `catalina.out` on Alfresco and you should have a better idea of the issue.
