### ISSUE TITLE
File "Alflytics.datasource.analysis.xml" not found during the installation process

### ISSUE THREAD

**Issue by david-ciamberlano** [fcorti/Alflytics#12]
Hi,

I'm trying to install Alflytics (locally on my mac) following the instructions on the official manual.

The installation process fails with the following error (taken from catalina.out):

`Generate multipart entity.0 - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35.36 by buildguy) : File 'Users/david/Workspace/work/pentaho-server/pentaho-solutions/system/Alflytics/endpoints/kettle/admin/../src/5.2/repository/Alflytics.datasource.analysis.xml' not found!!`

**Alflytics**: v5.0.EA 
**Pentaho**: pentaho-server-ce-7.0.0.0-25

The error seems to be related to the wrong initialization of the "uploadAnalysis" variable in the __addDataSources.ktr_ file (an initial '/' is missing)

**Comment by fcorti** [comment]
Hi @david-ciamberlano,

MacOs has not being tested and something might not work properly.
My recommendation is to use a Linux server.
I usually use a Virtual Machine on my Mac Laptop, for this purpose.

**Comment by jjrabadan** [comment]
Hi @fcorti ,

I'm trying to install Alflytics into my Apple Powerbook with Mac OS Sierra. I found the same error that @david-ciamberlano found when doing the same kind of installation:

2018/07/04 12:11:41 - Generate multipart entity.0 - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35.36 by buildguy) : File 'opt/pentaho-server/pentaho-solutions/system/Alflytics/endpoints/kettle/admin/../src/5.2/repository/Alflytics.datasource.analysis.xml' not found!!
org.pentaho.di.core.exception.KettleException: 
java.io.FileNotFoundException: File is not a normal file.
File is not a normal file.

is there anyway to solve this path problem?

Thank you very much!
Best regards,

JJRabadan.

**Comment by fcorti** [comment]
Hi JJRabadan,

Alflytics has not been tested on MacOS and the issue there is about paths into ETLs.
I hope this helps.

**Comment by fcorti** [comment]
Closing this becasue I don't see more discussion.
