### ISSUE TITLE
Extraction error

### ISSUE THREAD

**Issue by david-ciamberlano** [fcorti/Alflytics#13]
Hi,

I've managed to install and configure Alflytics_v5_EA but when I try to perform an "extraction" from Alfresco, I get the following error (from catalina.out):

```
[...]
REST call failed..0 - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35
.36 by buildguy) : La riga n. 1 ha causato l'annullamento: [{}], [https://xx.xx.xx.xx:8443/alfresco
/api/discovery], [GET], [<html><head>
2018/06/08 16:56:41 - REST call failed..0 - </head><body><p>Please <a href="/alfresco/api/discovery"
>log in</a>.</p>
2018/06/08 16:56:41 - REST call failed..0 - </body></html>
2018/06/08 16:56:41 - REST call failed..0 - ], [401]
2018/06/08 16:56:41 - REST call failed..0 - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35
.36 by buildguy) : REST call failed. Please check you Alfresco instance is available.
[...]
```

The Alfresco instance is available and reachable from the alflytics server (it responds with the xml fragment visible in the log).
It seems like the basic authetication used by the api/discovery call does not respond in the correct way.

Is there a workaround to resolve this problem? 

**Alflytics**
Alflytics_v5_EA
pentaho-server-ce-7.0.0.0-25
SO: centos 7.3

**Alfresco**:
Alfresco Content Service: 5.2.3
SSL enabled on the 8443 port
Authentication: internal + Active Directory

**Comment by fcorti** [comment]
Hi David,

Can you please try with HTTP first?
I have experienced in the past some issue in communication using the HTTPS protocol.
Please let me know how it goes here, so we can decide to close the issue do more tests.

Cheers.

**Comment by david-ciamberlano** [comment]
Hi,

thank you for the response.
I've done more tests and I can confirm that Alflytics can login with both http and https protocols.

It could be an Alfresco issue (related to this one: https://issues.alfresco.com/jira/browse/MNT-15819). 
I would need to do some in-depth tests. Could you point me to the java class that perform the Http(s) call to the alfresco REST service?

Thank you.

**Comment by david-ciamberlano** [comment]
Finally I resolved the issue.

The "Browser Based Automatic Login" option (in _Admin Console_->_Directory Management_) was setted to "internal". I switched it to _disabled_ and now I'm able to perform extractions in Alflytics.

I hope this will be useful to others.
