### ISSUE TITLE
put reports into Alfresco 

### ISSUE THREAD

**Issue by Dnhatsave** [fcorti/Alflytics#17]
hi Corti, 

im using a PDI to execute the job ''**report all**'', and i would like publish the reports into the alfresco, I've followed the steps described on page 44 -5.3.3 of the Alflytics-Manual , also a i've update the table DWH_REPORTS setting the correct values for ALF_FTP_PORT and ALF_FTP_HOST.
the good news is that I got 9 reports published successfully in alfresco, the bad news is had the following error during the execution:

2018/09/19 14:11:01 - Put a file with FTP - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Error putting to FTP : Connection refused (Connection refused)
2018/09/19 14:11:01 - Put a file with FTP - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : java.net.ConnectException: Connection refused (Connection refused)
2018/09/19 14:11:01 - Put a file with FTP - 	at java.net.PlainSocketImpl.socketConnect(Native Method)
2018/09/19 14:11:01 - Put a file with FTP - 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2018/09/19 14:11:01 - Put a file with FTP - 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2018/09/19 14:11:01 - Put a file with FTP - 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2018/09/19 14:11:01 - Put a file with FTP - 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2018/09/19 14:11:01 - Put a file with FTP - 	at java.net.Socket.connect(Socket.java:589)
2018/09/19 14:11:01 - Put a file with FTP - 	at com.enterprisedt.util.proxy.PlainSocket.createPlainSocket(PlainSocket.java:122)
2018/09/19 14:11:01 - Put a file with FTP - 	at com.enterprisedt.net.ftp.FTPControlSocket.<init>(FTPControlSocket.java:366)
2018/09/19 14:11:01 - Put a file with FTP - 	at com.enterprisedt.net.ftp.FTPClient.connect(FTPClient.java:970)
2018/09/19 14:11:01 - Put a file with FTP - 	at org.pentaho.di.job.entries.ftpput.JobEntryFTPPUT.execute(JobEntryFTPPUT.java:597)
2018/09/19 14:11:01 - Put a file with FTP - 	at org.pentaho.di.job.Job.execute(Job.java:724) 	at org.pentaho.di.job.entries.job.JobEntryJobRunner.run(JobEntryJobRunner.java:69)
2018/09/19 14:11:01 - Put a file with FTP - 	at java.lang.Thread.run(Thread.java:748)

Could you help me to solve this issue?

Thank you.

Dercio.

**Comment by fcorti** [comment]
Hi Dercio,

I'm confused: you say that you have the 9 reports published successfully in alfresco but you have an error.
Can you please clarify?

**Comment by Dnhatsave** [comment]
yes corti,

I’ve 9 reports successfully published in alfresco I expected to see more because during the publication I had the FTP error quoted above.

**Comment by fcorti** [comment]
Can you please share the content of the table DM_REPORTS?

**Comment by Dnhatsave** [comment]
Hi Corti, 
I already discovered the problem, I'had only 9 reports were published because the Row 10 is not updated. 

Yes, Here is my DWM_REPORTS table

[DWM_REPORTS.docx](https://github.com/fcorti/Alflytics/files/2477856/DWM_REPORTS.docx).

Best regards,
Dercio.

**Comment by fcorti** [comment]
Well done!

Closing the issue, then.
