### ISSUE TITLE
Get data from Alfresco using spoon

### ISSUE THREAD

**Issue by Dnhatsave** [fcorti/Alflytics#18]
hi one more time,

im tryng to get data from the alfresco instance usign spoon and mysql workbench 6.3 as database for data warehouse.
i've execute the job "**Get all**" and i had the following erros:

No tran_Status found. Transformation status checking not available.
2018/09/19 16:39:49 - Alflytics - launch DDL statement: 
2018/09/19 16:39:49 - Alflytics - INSERT INTO `OPE_ALF_AUDIT_ACCESSES`(`INSTANCE_ID`,`ID`,`USER`,`USER_LOGIN`,`USER_LOGIN_FAILURE`,`USER_LOGOUT`,`TIME`,`ACTION`,`NODE_PATH`) VALUES (1,1,'admin','admin',null,null,CONVERT_TZ(STR_TO_DATE('2018-09-05T15:04:03.10', '%Y-%m-%dT%H:%i:%s.%f'),'+02:00','+00:00'),null,null)
2018/09/19 16:39:50 - Alflytics - 1 statement executed
2018/09/19 16:39:50 - SQL creation.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2018/09/19 16:39:50 - SQL creation.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleValueException: 
2018/09/19 16:39:50 - SQL creation.0 - Javascript error: 
2018/09/19 16:39:50 - SQL creation.0 - SyntaxError: String contains control character (_getInserts_#3)
2018/09/19 16:39:50 - SQL creation.0 - 
2018/09/19 16:39:50 - SQL creation.0 - 	at org.pentaho.di.trans.steps.scriptvalues_mod.ScriptValuesMod.addValues(ScriptValuesMod.java:475)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.pentaho.di.trans.steps.scriptvalues_mod.ScriptValuesMod.processRow(ScriptValuesMod.java:541)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/09/19 16:39:50 - SQL creation.0 - 	at java.lang.Thread.run(Thread.java:748)
2018/09/19 16:39:50 - SQL creation.0 - Caused by: org.mozilla.javascript.EcmaError: SyntaxError: String contains control character (_getInserts_#3)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:146)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.NativeJSON.execIdCall(NativeJSON.java:122)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.gen._getInserts__84._c_getInserts_1(_getInserts_:3)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.gen._getInserts__84.call(_getInserts_)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.gen.script_87._c_script_0(script:2)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.gen.script_87.call(script)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.gen.script_87.call(script)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.mozilla.javascript.gen.script_87.exec(script)
2018/09/19 16:39:50 - SQL creation.0 - 	at org.pentaho.di.trans.steps.scriptvalues_mod.ScriptValuesMod.addValues(ScriptValuesMod.java:388)
2018/09/19 16:39:50 - SQL creation.0 - 	... 3 more
2018/09/19 16:39:50 - Get Alfresco audit trail from staging in operational - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected!
2018/09/19 16:39:50 - Source table.0 - Finished reading query, closing connection.

2018/09/19 16:39:50 - Get Alfresco audit trail from staging in operational - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected!

Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Row nr 1 causing abort : [{"query":{"query": "(((TYPE:\"cm:content\") OR (TYPE:\"cm:folder\")) AND NOT (TYPE:\"cm:systemfolder\") AND (@cm:modified:[\"2001-01-01T00:00:00.000Z\" TO MAX]))","language":"afts"},"paging":{"maxItems":1,"skipCount":1000000000}}], [http://172.31.4.120:8080/alfresco/api/-default-/public/search/versions/1/search], [POST], [{"error":{"errorKey":"framework.exception.ApiDefault","statusCode":500,"briefSummary":"08191512 ","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions","descriptionURL":"https://api-explorer.alfresco.com","logId":"4a8578ac-f28e-4086-9e70-f179ac657326"}}], [500]
2018/09/19 16:39:53 - Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Rest call failed.
2018/09/19 16:39:53 - Abort.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=1)
2018/09/19 16:39:53 - Get Alfresco counter - Transformation detected one or more steps with errors.
2018/09/19 16:39:53 - Get Alfresco counter - Transformation is killing the other steps!
2018/09/19 16:39:53 - Get Alfresco counter - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected!

after running this job I could notice that some tables were not filled for some reason, I will  attach some screen captures to help analyze the problem.

I appreciate your help.

![screenshot from 2018-09-19 17-43-48](https://user-images.githubusercontent.com/43370602/45764949-216e5400-bc34-11e8-8a65-bc25df690ec4.png)
![screenshot from 2018-09-19 17-46-01](https://user-images.githubusercontent.com/43370602/45764951-2206ea80-bc34-11e8-90fa-3b60912c6293.png)

**Comment by fcorti** [comment]
Hi Decio,

What happens if you run the following query using the MySql Workbench?

`OPE_ALF_AUDIT_ACCESSES(INSTANCE_ID,ID,USER,USER_LOGIN,USER_LOGIN_FAILURE,USER_LOGOUT,TIME,ACTION,NODE_PATH) VALUES (1,1,'admin','admin',null,null,CONVERT_TZ(STR_TO_DATE('2018-09-05T15:04:03.10', '%Y-%m-%dT%H:%i:%s.%f'),'+02:00','+00:00'),null,null)
`

I think there is a syntax error into this query, for your version of MySql.

**Comment by Dnhatsave** [comment]
Thanks for the atention @fcorti 

you forgot to mention a "INSERT INTO" command.

I've run the query on workbench as recommended  and i had the following error:

Error Code: 1062. Duplicate entry '1-1' for key 'PRIMARY'

is this really a problem of MySql version? if yes, i like to know wich version of MySql you recommend.
i'm using workbech 6.3 and mysql 5.7.23.


Thank you,
Dercio.

**Comment by fcorti** [comment]
Ok, this make sense because the row has been probably inserted.
What if you replace the ID value with another not already in present as ID?
Is the Insert command working?

**Comment by Dnhatsave** [comment]
It work, I've change the ID value for 2 

but I still do not understand why this happens..

**Comment by fcorti** [comment]
Can you please check if you have a duplicated audit entry with ID = 1 into the STG_ALF_AUDIT_... table?
I'm aware that sometimes Alfresco generates a duplicated audit entry with the same ID and this cause the primary key violation. Most of the times it is a problem on Alfresco side.

I'm going to close this ticket for this issue.

Please open another sharing the context of problem, if needed.

Thanks.
