### ISSUE TITLE
No jobs files on Pentaho Analytics platform path /public/Alflytics/ETL

### ISSUE THREAD

**Issue by billydekid** [fcorti/Alflytics#26]
Hi,
I'm having issue on importing Pentaho repository (section 3.4.1.4 Importing the Pentaho repository).
After restarting the server, no files generated on ETL and OLAP directories, only sub-folders was generated (as attached).
Is it a normal results or not?

Ubuntu 16.04
Pentaho Analytics 7.1
PostgreSQL 9.5
Alflytics 5.0

![screenshot-192 168 56 102_8080-2020 07 19-17_07_34](https://user-images.githubusercontent.com/6064187/87872518-8d15d980-c9e3-11ea-8a62-c4b71fe997d0.png)

Regards,
[bayu]

**Comment by billydekid** [comment]
After continuing installation, all files appear finally on PDI. Something like a kind of file type filtering on pentaho analytics file browser.

**Comment by fcorti** [comment]
Good job!
