### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by fcorti** [fcorti/Alflytics#5]
The problems found from some user are:
1. Unzipping Pentaho in Desktop will cause the paths to be too long. Suggest to unzip it in C:.
2. The file name web.xml.2017-07-08T14:09:53.033Z  has invalid windows characters.
3. Uncompress pentaho to the desktop is also not a good idea.The problem is that there are jar files inside with big names which makes the destination path too big for windows!

**Comment by fcorti** [comment]
The issue is on _installAlflytics.kjb
Changed this: 

parent_job.setVariable("now", (new Date()).toISOString));

to this:

parent_job.setVariable("now", (new Date()).toISOString().replace(/\:/g, ""));

Waiting to push the change in the repo...

**Comment by psedwards99** [comment]
Hi Francesco,

Do plan to push this change soon? I was looking to install Alflytics at one of our Alfresco customers who use Windows.

Thanks
Paul

**Comment by fcorti** [comment]
Hi psedwards99,

In most of cases it is not an issue and I'm aware about succesfull installations on win.
I suggest you to try in a dev env so you could share your feedback and confirm it works well.

Let me know at fcorti at gmail dot com (or here) if you have issues.

**Comment by fcorti** [comment]
Added a patch to the endpoints/kettle/admin/_installAlflytics.kjb.
Updated also the pre-relase.
