### ISSUE TITLE
Problem with Jobs when running in Data integration !!!!

### ISSUE THREAD

**Issue by Danielagarcia1309** [fcorti/Alflytics#9]
Good Afertnoon
I have problems with the execution of the Jobs that are generated in the integration with Alfresco, I generated the following problem in the majority of Jobs:

`2017/10/11` 15:57:40 - Dynamic SQL row.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Because of an error, this step can't continue: 
2017/10/11 15:57:40 - Dynamic SQL row.0 - Error obtaining fields for this step
2017/10/11 15:57:40 - Dynamic SQL row.0 - 
2017/10/11 15:57:40 - Dynamic SQL row.0 - Couldn't get field info from []
2017/10/11 15:57:40 - Dynamic SQL row.0 - 
2017/10/11 15:57:40 - Dynamic SQL row.0 - La consulta no retornó ningún resultado.
2017/10/11 15:57:40 - Get Alfresco classes in variable - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected! `

also sends me to this route too 👍 

> http://localhost:8091/alfresco/api/discovery

my port is 8091 where Alfresco runs, but there is a username and password that I already try with the one we normally use with alfresco but it will not let me enter

You could help me with this error Thank you very much

**Comment by fcorti** [comment]
Hi Daniela,

Usually this error is a side effect of something that is not working, during the installation task.
Most of the times it depends on the pentaho URL, if not installed on the default localhost:8080.
In which URL/port your pentaho instance is running?
If it is not on localhost:8080, did you update the jobs as described on page 29 (paragraph 3.4.1.5) of the manual?

Cheers.

**Comment by Danielagarcia1309** [comment]
Hi
thank you for answering me
the pentaho is running in http://localhost:8080/pentaho/   runs without problem. Given that we are developing it with postgresql
 I'm looking at paragraph 3.4.1.5 and it sends me in the chapter that sends me sends another chapter of scalability, there is a section in which, we talk about Kitchen.bat, when I run this as it says in the guide, I get this script error to the last
Javascript Error:
SyntaxError: Unexpected token: <(script # 5)

in org.pentaho.di.trans.steps.scriptvalues_mod.ScriptValuesMod.addValues ​​(ScriptValuesMod.java:475)
in org.pentaho.di.trans.steps.scriptvalues_mod.ScriptValuesMod.processRow (ScriptValuesMod.java:541)
in org.pentaho.di.trans.step.RunThread.run (RunThread.java:62)
in java.lang.Thread.run (Thread.java:748)
Caused by: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected Token: <(script # 5)
in org.mozilla.javascript.ScriptRuntime.constructError (ScriptRuntime.java:3785)
in org.mozilla.javascript.ScriptRuntime.constructError (ScriptRuntime.java:3763)
in org.mozilla.javascript.NativeJSON.parse (NativeJSON.java:146)
in org.mozilla.javascript.NativeJSON.execIdCall (NativeJSON.java:122)
in org.mozilla.javascript.IdFunctionObject.call (IdFunctionObject.java:129)
at org.mozilla.javascript.optimizer.OptRuntime.call1 (OptRuntime.java:66)
in org.mozilla.javascript.gen.script_1._c_script_0 (script: 5)
in org.mozilla.javascript.gen.script_1.call (script)
in org.mozilla.javascript.ContextFactory.doTopCall (ContextFactory.java:426)
in org.mozilla.javascript.ScriptRuntime.doTopCall (ScriptRuntime.java:3178)
in org.mozilla.javascript.gen.script_1.call (script)
in org.mozilla.javascript.gen.script_1.exec (script)
in org.pentaho.di.trans.steps.scriptvalues_mod.ScriptValuesMod.addValues ​​(ScriptValuesMod.java:388)
... 3 more
2017/10/17 15:23:35 - Creation of the result.0 - ERROR (version 7.1.0.0-12, build 1 of 2017-05-16 17.18.02 by buildguy): unexpected error
2017/10/17 15:23:35 - Creation of the result.0 - ERROR (version 7.1.0.0-12, build 1 of 2017-05-16 17.18.02 by buildguy): org.pentaho.di.core.exception . KettleValueException:
2017/10/17 15:23:35 - Creation of results. 0 - Javascript Error:
2017/10/17 15:23:35 - Result Creation.0 - SyntaxError: Unexpected Token: <(script # 5)
What could it be ?

You could help me with this error Thank you very much

**Comment by fcorti** [comment]
Assumed as answered.
Let me know if it is not.
